apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openapi
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://cgrllfayg0-vpce-0b75e58a445147377.execute-api.ap-southeast-1.amazonaws.com/uat
      title: API Base URL
      icon: web
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental

